import type { Metadata } from "next";
import { Hind_Siliguri} from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/NavBar";
import Footer from "@/Components/Footer";
import Marquee from "@/Components/Marquee";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";

const hindSiliguri = Hind_Siliguri({
  subsets: ["latin", "bengali"],
  weight: ["400", "500", "600", "700"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${hindSiliguri.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar/>
        <Suspense fallback={<div>Loading products...</div>}>
        <Marquee />
      </Suspense>
        {children}
        <ToastContainer position="top-center" autoClose={3000} />
        <Footer/>

        </body>
    </html>
  );
}
